/**
 * Onboarding-style coding lessons for the Coding module.
 * Teaches prompt engineering for AI-assisted web development.
 * Used to seed dev and prod databases.
 * IDs: code-1-easy through code-5-easy, code-6-medium through code-10-medium, code-11-hard through code-15-hard
 */

const CODE_IDS = [
  "code-1-easy", "code-2-easy", "code-3-easy", "code-4-easy", "code-5-easy",
  "code-6-medium", "code-7-medium", "code-8-medium", "code-9-medium", "code-10-medium",
  "code-11-hard", "code-12-hard", "code-13-hard", "code-14-hard", "code-15-hard",
];

export const codingLessons = [
  {
    id: CODE_IDS[0],
    title: "Describe what the user sees",
    instruction: "Add a hero section to this webpage.",
    hint: "Think about what text it shows, what it looks like, and what the user can do on it.",
    starterCode: "<html>\n  <body>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_hero_section", description: "The generated code contains a visible section at the top of the page.", method: "static_analysis", weight: 1, required: true },
        { id: "has_heading", description: "The hero section has a heading that describes what the page or product is.", method: "static_analysis", weight: 2, required: true },
        { id: "has_subtext_or_cta", description: "The hero section has either a subheading, a description, or a call to action button.", method: "llm_judge", weight: 2, required: false },
        { id: "visually_distinct", description: "The hero section is visually distinct from the rest of the page through color, size, or spacing.", method: "llm_judge", weight: 1, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 3 out of 6.",
      perfectScore: "All four criteria pass.",
    },
    failState: { condition: "has_hero_section passes but has_heading fails.", nudge: "There's a section there, but what is this page about? Give it a headline." },
    successState: { condition: "Passing condition is met.", feedback: "Good. You described what the user sees and AI filled it in. That's how every feature starts." },
    lessonTakeaway: "Describing what the user sees is more useful than describing the code you want written.",
  },
  {
    id: CODE_IDS[1],
    title: "Specify your stack",
    instruction: "Build a navigation bar for this app.",
    hint: "AI doesn't know what framework or styling approach you're using. Tell it.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_navbar", description: "The generated code contains a navigation bar element.", method: "static_analysis", weight: 1, required: true },
        { id: "has_nav_links", description: "The navbar contains at least two navigation links.", method: "static_analysis", weight: 2, required: true },
        { id: "uses_tailwind", description: "The navbar is styled using Tailwind CSS classes, not inline styles or a separate stylesheet.", method: "static_analysis", weight: 2, required: false },
        { id: "visually_complete", description: "The navbar looks like a real navbar: horizontal layout, readable links, and some background color or border.", method: "llm_judge", weight: 1, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 3 out of 6.",
      perfectScore: "All four criteria pass.",
    },
    failState: { condition: "has_navbar passes but uses_tailwind fails.", nudge: "The navbar is there but AI didn't use Tailwind. Did you tell it what styling system to use?" },
    successState: { condition: "Passing condition is met.", feedback: "When you tell AI your stack, it stops guessing and starts fitting." },
    lessonTakeaway: "Always name your tech stack in the prompt. AI defaults to its own assumptions otherwise.",
  },
  {
    id: CODE_IDS[2],
    title: "One feature at a time",
    instruction: "Add a contact form to this page. Just the form, nothing else.",
    hint: "Keep your prompt focused on only the form. Don't ask for anything else at the same time.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body>\n    <h1 class=\"text-2xl font-bold p-8\">Contact Us</h1>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_form", description: "The generated code contains a form element.", method: "static_analysis", weight: 1, required: true },
        { id: "has_required_fields", description: "The form has at least a name field, an email field, and a message field.", method: "static_analysis", weight: 2, required: true },
        { id: "has_submit_button", description: "The form has a submit button.", method: "static_analysis", weight: 1, required: true },
        { id: "nothing_else_changed", description: "The existing h1 heading is still present and nothing outside the form was modified.", method: "static_analysis", weight: 2, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 4 out of 6.",
      perfectScore: "All four criteria pass.",
    },
    failState: { condition: "has_form passes but nothing_else_changed fails.", nudge: "AI changed more than just the form. Try telling it exactly what to add and what to leave alone." },
    successState: { condition: "Passing condition is met.", feedback: "One prompt, one task. That's how you stay in control of what AI builds." },
    lessonTakeaway: "Scoping your prompt to one feature at a time keeps AI from making changes you didn't ask for.",
  },
  {
    id: CODE_IDS[3],
    title: "Describe behavior, not code",
    instruction: "Make the sign up button on this page do something when clicked.",
    hint: "Don't tell AI what code to write. Tell it what the user should experience.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <button class=\"bg-blue-500 text-white px-4 py-2 rounded\">Sign Up</button>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_click_behavior", description: "The button has a click handler or event listener attached to it.", method: "static_analysis", weight: 2, required: true },
        { id: "behavior_is_meaningful", description: "The behavior is something a real user would expect: a modal, a redirect, a form appearing, or a confirmation message. Not just a console.log.", method: "llm_judge", weight: 2, required: true },
        { id: "prompt_used_user_language", description: "The user's prompt described the experience from the user's perspective, not in technical terms like 'add an onclick handler'.", method: "llm_judge", weight: 2, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 4 out of 6.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "has_click_behavior passes but behavior_is_meaningful fails.", nudge: "The button does something, but it's not meaningful to a user. What should they actually see or experience?" },
    successState: { condition: "Passing condition is met.", feedback: "AI figures out the how when you give it the what. You don't need to write the code in your prompt." },
    lessonTakeaway: "Describe what the user experiences, not what the code should do. AI handles the implementation.",
  },
  {
    id: CODE_IDS[4],
    title: "Set the guardrails",
    instruction: "Change the color of the header on this page.",
    hint: "Think about how to tell AI what to change without letting it touch anything else.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <header class=\"bg-gray-800 text-white p-4\">\n      <h1 class=\"text-2xl font-bold\">My App</h1>\n      <nav class=\"mt-2\">\n        <a href=\"#\" class=\"text-gray-300 mr-4\">Home</a>\n        <a href=\"#\" class=\"text-gray-300 mr-4\">About</a>\n        <a href=\"#\" class=\"text-gray-300\">Contact</a>\n      </nav>\n    </header>\n    <main class=\"mt-8\">\n      <p class=\"text-gray-600\">Welcome to my app.</p>\n    </main>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "header_color_changed", description: "The background color of the header element is different from the original gray-800.", method: "static_analysis", weight: 2, required: true },
        { id: "nav_links_intact", description: "The nav links are still present and unchanged.", method: "static_analysis", weight: 2, required: true },
        { id: "main_content_intact", description: "The main content below the header is untouched.", method: "static_analysis", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "header_color_changed passes but main_content_intact or nav_links_intact fails.", nudge: "AI changed more than the header. Try explicitly telling it what not to touch." },
    successState: { condition: "Passing condition is met.", feedback: "Telling AI what to leave alone is just as important as telling it what to change." },
    lessonTakeaway: "Always tell AI what not to modify. Without guardrails, it will helpfully break things that were already working.",
  },
  {
    id: CODE_IDS[5],
    title: "Report the bug precisely",
    instruction: "This form submits even when the email field is empty. Fix it.",
    hint: "Tell AI exactly what the bug is, where it is, and what the correct behavior should be.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <form id=\"contactForm\" class=\"space-y-4\">\n      <input type=\"text\" placeholder=\"Email\" class=\"border p-2 w-full rounded\" />\n      <button type=\"submit\" class=\"bg-blue-500 text-white px-4 py-2 rounded\">Submit</button>\n    </form>\n    <script>\n      document.getElementById('contactForm').addEventListener('submit', function(e) {\n        e.preventDefault();\n        alert('Form submitted!');\n      });\n    </script>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_validation", description: "The form now validates that the email field is not empty before submitting.", method: "static_analysis", weight: 2, required: true },
        { id: "shows_error_message", description: "When the user submits with an empty email, they see an error message telling them the field is required.", method: "llm_judge", weight: 2, required: true },
        { id: "valid_submission_still_works", description: "When the email field is filled in, the form still submits successfully.", method: "llm_judge", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "has_validation fails.", nudge: "The form still submits when the email is empty. Did you tell AI specifically what behavior is wrong and what it should be instead?" },
    successState: { condition: "Passing condition is met.", feedback: "A precise bug report gets a precise fix. The more specific you are about what's wrong, the less AI has to guess." },
    lessonTakeaway: "When reporting a bug, always include what is happening, where it is, and what should happen instead.",
  },
  {
    id: CODE_IDS[6],
    title: "Ask for the plan first",
    instruction: "You need to add a dark mode toggle to this app. Before asking AI to write any code, ask it to plan the approach.",
    hint: "Prompt AI to think through the steps, the components involved, and any edge cases before it writes a single line.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8 bg-white text-black\">\n    <header class=\"mb-8\">\n      <h1 class=\"text-2xl font-bold\">My App</h1>\n    </header>\n    <main>\n      <p>Welcome to my app.</p>\n    </main>\n  </body>\n</html>",
    grading: {
      method: "llm_judge",
      criteria: [
        { id: "prompt_asked_for_plan", description: "The user's prompt explicitly asked AI to plan or outline the approach before writing code.", method: "llm_judge", weight: 2, required: true },
        { id: "ai_output_is_a_plan", description: "The AI response contains a structured plan, steps, or outline rather than jumping straight into code.", method: "llm_judge", weight: 2, required: true },
        { id: "plan_covers_edge_cases", description: "The plan mentions at least one edge case or consideration, such as persisting the user's preference or handling system defaults.", method: "llm_judge", weight: 2, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 4 out of 6.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "ai_output_is_a_plan fails.", nudge: "AI went straight to writing code. Try explicitly telling it to plan first and not write any code yet." },
    successState: { condition: "Passing condition is met.", feedback: "AI makes better decisions when it plans first. A plan prompt is always worth it on anything bigger than a single element." },
    lessonTakeaway: "Ask AI to outline its approach before writing code. It catches problems early that would cost you three more prompts to fix.",
  },
  {
    id: CODE_IDS[7],
    title: "Prompt for edge cases",
    instruction: "This page fetches and displays a list of users. Make it handle what happens when the fetch fails or the list is empty.",
    hint: "Explicitly name the edge cases in your prompt. AI won't add them unless you ask.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <h1 class=\"text-2xl font-bold mb-4\">Users</h1>\n    <ul id=\"userList\" class=\"space-y-2\"></ul>\n    <script>\n      fetch('https://jsonplaceholder.typicode.com/users')\n        .then(res => res.json())\n        .then(users => {\n          const list = document.getElementById('userList');\n          users.forEach(user => {\n            const li = document.createElement('li');\n            li.textContent = user.name;\n            list.appendChild(li);\n          });\n        });\n    </script>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "handles_fetch_failure", description: "The code catches fetch errors and shows the user a message when the request fails.", method: "static_analysis", weight: 2, required: true },
        { id: "handles_empty_list", description: "The code checks if the returned list is empty and shows the user a message instead of an empty page.", method: "llm_judge", weight: 2, required: true },
        { id: "error_messages_are_user_friendly", description: "The error and empty state messages are written for a real user, not a developer. No raw error objects or console output.", method: "llm_judge", weight: 2, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 4 out of 6.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "handles_fetch_failure or handles_empty_list fails.", nudge: "AI didn't cover all the edge cases. Try listing them explicitly in your prompt: what happens when the request fails, and what happens when there's nothing to show." },
    successState: { condition: "Passing condition is met.", feedback: "AI builds for the happy path by default. Edge cases only show up in the code when they show up in the prompt." },
    lessonTakeaway: "List every edge case you can think of in the prompt. AI won't add defensive behavior unless you name it.",
  },
  {
    id: CODE_IDS[8],
    title: "Iterate without starting over",
    instruction: "This card component is close but not right yet. Fix only the spacing and make the title larger, without rewriting the whole prompt.",
    hint: "Write a short follow-up prompt that targets exactly what needs to change. Don't describe the whole component again.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <div class=\"border rounded p-2 w-64\">\n      <h2 class=\"text-sm font-bold\">Card Title</h2>\n      <p class=\"text-gray-600\">This is the card description text.</p>\n      <button class=\"bg-blue-500 text-white px-2 py-1 rounded\">Action</button>\n    </div>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "title_is_larger", description: "The card title is visually larger than in the original, using a bigger text size class.", method: "static_analysis", weight: 2, required: true },
        { id: "spacing_improved", description: "The padding or gap between elements inside the card is larger than the original.", method: "static_analysis", weight: 2, required: true },
        { id: "nothing_else_changed", description: "The card content, button, and description text are all unchanged. Only spacing and title size were modified.", method: "llm_judge", weight: 2, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 4 out of 6.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "title_is_larger or spacing_improved fails.", nudge: "The changes didn't land. Try being more specific about which element needs more space and how much bigger the title should be." },
    successState: { condition: "Passing condition is met.", feedback: "A targeted follow-up prompt is faster than rewriting everything. You only need to describe what changed." },
    lessonTakeaway: "Treat AI as a conversation loop. When something is 70% right, write a focused follow-up instead of starting over.",
  },
  {
    id: CODE_IDS[9],
    title: "Give AI the context it's missing",
    instruction: "Add a logout button to the navbar. This app uses a global auth state stored in a variable called `authStore`.",
    hint: "AI doesn't know about your app's architecture unless you tell it. Include the relevant context in your prompt.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body>\n    <header class=\"bg-gray-800 text-white p-4 flex items-center justify-between\">\n      <h1 class=\"text-xl font-bold\">My App</h1>\n      <nav class=\"flex gap-4\">\n        <a href=\"#\" class=\"text-gray-300\">Dashboard</a>\n        <a href=\"#\" class=\"text-gray-300\">Settings</a>\n      </nav>\n    </header>\n    <script>\n      const authStore = {\n        user: { name: 'Mikhail' },\n        logout: function() {\n          this.user = null;\n          alert('Logged out');\n        }\n      };\n    </script>\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "has_logout_button", description: "The navbar contains a logout button.", method: "static_analysis", weight: 1, required: true },
        { id: "calls_auth_store_logout", description: "The logout button calls authStore.logout() when clicked.", method: "static_analysis", weight: 3, required: true },
        { id: "button_is_in_navbar", description: "The logout button is placed inside the existing navbar, not below it or elsewhere on the page.", method: "llm_judge", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "calls_auth_store_logout fails.", nudge: "The button is there but it doesn't connect to authStore. Did you tell AI about the existing auth variable in your prompt?" },
    successState: { condition: "Passing condition is met.", feedback: "When you include your app's context, AI writes code that fits. Without it, you get generic code you have to rewrite by hand." },
    lessonTakeaway: "Always tell AI about the relevant parts of your existing codebase before asking it to add something new.",
  },
  {
    id: CODE_IDS[10],
    title: "Describe a UI without technical terms",
    instruction: "Redesign this pricing card using only visual and behavioral language in your prompt. No framework names, no class names, no CSS properties.",
    hint: "Describe colors, sizes, layout, and what happens on hover the way you'd describe it to a designer, not a developer.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-16 bg-gray-100 flex justify-center\">\n    <div class=\"border p-4 w-64 bg-white\">\n      <h2 class=\"text-lg font-bold\">Pro Plan</h2>\n      <p class=\"text-2xl\">$29/mo</p>\n      <ul>\n        <li>Feature one</li>\n        <li>Feature two</li>\n        <li>Feature three</li>\n      </ul>\n      <button class=\"bg-blue-500 text-white px-4 py-2 mt-4\">Get Started</button>\n    </div>\n  </body>\n</html>",
    grading: {
      method: "llm_judge",
      criteria: [
        { id: "prompt_uses_no_technical_terms", description: "The user's prompt contains no CSS class names, no framework-specific terms, and no code-level instructions. It describes the design in plain visual language.", method: "llm_judge", weight: 3, required: true },
        { id: "card_looks_visually_improved", description: "The redesigned card is visually more polished than the original, with better spacing, typography, or color.", method: "llm_judge", weight: 2, required: true },
        { id: "card_has_hover_or_interactive_state", description: "The card or its button has some kind of hover or interactive visual state.", method: "static_analysis", weight: 1, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 5 out of 6.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "prompt_uses_no_technical_terms fails.", nudge: "Your prompt included technical terms. Try describing it the way you'd explain it to someone who doesn't code. What does it look like? What happens when you interact with it?" },
    successState: { condition: "Passing condition is met.", feedback: "Describing the experience is often more reliable than describing the implementation. AI translates visual language into code well." },
    lessonTakeaway: "You don't need to know the technical term for something to prompt it effectively. Visual and behavioral descriptions work.",
  },
  {
    id: CODE_IDS[11],
    title: "Reset the context mid-session",
    instruction: "You've been building this app across a long session and AI is starting to lose track. Write a context reset prompt that gets it back on track before adding a new feature.",
    hint: "Summarize what's been built, what the current state is, and exactly what you need next. Treat it like a briefing.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body>\n    <header class=\"bg-blue-600 text-white p-4 flex justify-between items-center\">\n      <h1 class=\"text-xl font-bold\">TaskFlow</h1>\n      <button class=\"text-sm bg-white text-blue-600 px-3 py-1 rounded\">Logout</button>\n    </header>\n    <main class=\"p-8\">\n      <h2 class=\"text-lg font-bold mb-4\">Your Tasks</h2>\n      <ul id=\"taskList\" class=\"space-y-2\">\n        <li class=\"border p-3 rounded bg-white\">Buy groceries</li>\n        <li class=\"border p-3 rounded bg-white\">Finish project report</li>\n      </ul>\n    </main>\n  </body>\n</html>",
    grading: {
      method: "llm_judge",
      criteria: [
        { id: "prompt_summarizes_current_state", description: "The user's prompt describes what has already been built in the app.", method: "llm_judge", weight: 2, required: true },
        { id: "prompt_states_next_task_clearly", description: "The user's prompt clearly states what the next feature or change is.", method: "llm_judge", weight: 2, required: true },
        { id: "new_feature_is_added_correctly", description: "The AI output adds the requested feature correctly without breaking existing elements.", method: "llm_judge", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "new_feature_is_added_correctly fails.", nudge: "AI got confused and broke something or added the wrong thing. Try writing a cleaner summary of what exists and what you need next." },
    successState: { condition: "Passing condition is met.", feedback: "A deliberate context reset keeps output quality from degrading in long sessions. It's one of the highest-leverage prompting habits." },
    lessonTakeaway: "In long sessions, AI loses coherence. A summary prompt that recaps the current state and the next step gets you back on track fast.",
  },
  {
    id: CODE_IDS[12],
    title: "Ask AI to audit its own output",
    instruction: "Ask AI to review the code it just generated and find any security issues, hardcoded values, or missing error states.",
    hint: "Don't ask 'does this look good?' Ask it to check for specific things.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8\">\n    <form id=\"loginForm\" class=\"space-y-4 max-w-sm\">\n      <input type=\"text\" id=\"username\" placeholder=\"Username\" class=\"border p-2 w-full rounded\" />\n      <input type=\"password\" id=\"password\" placeholder=\"Password\" class=\"border p-2 w-full rounded\" />\n      <button type=\"submit\" class=\"bg-blue-500 text-white px-4 py-2 rounded w-full\">Login</button>\n    </form>\n    <script>\n      document.getElementById('loginForm').addEventListener('submit', function(e) {\n        e.preventDefault();\n        const username = document.getElementById('username').value;\n        const password = document.getElementById('password').value;\n        fetch('http://api.myapp.com/login', {\n          method: 'POST',\n          body: JSON.stringify({ username, password, apiKey: '12345-hardcoded-key' })\n        }).then(res => res.json()).then(data => {\n          window.location.href = '/dashboard';\n        });\n      });\n    </script>\n  </body>\n</html>",
    grading: {
      method: "llm_judge",
      criteria: [
        { id: "prompt_requests_specific_audit", description: "The user's prompt asks AI to check for specific issues like security vulnerabilities, hardcoded values, or missing error handling, not just 'review this'.", method: "llm_judge", weight: 2, required: true },
        { id: "ai_identifies_hardcoded_key", description: "The AI response identifies the hardcoded API key as a problem.", method: "llm_judge", weight: 2, required: true },
        { id: "ai_identifies_missing_error_handling", description: "The AI response identifies that the fetch call has no error handling.", method: "llm_judge", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "ai_identifies_hardcoded_key or ai_identifies_missing_error_handling fails.", nudge: "AI gave a surface-level review. Try asking it to specifically look for hardcoded values and missing error states." },
    successState: { condition: "Passing condition is met.", feedback: "AI is a sharper reviewer when you give it a checklist. A vague 'review this' gets vague feedback." },
    lessonTakeaway: "When asking AI to review its own output, give it specific things to look for. Specific audits catch real problems.",
  },
  {
    id: CODE_IDS[13],
    title: "Write a spec, then build from it",
    instruction: "Write a one-paragraph spec for a task manager app, then use that spec as your prompt to scaffold the full app structure.",
    hint: "Your spec should cover what the app does, who uses it, what the core features are, and what the tech stack is. Then paste it directly as your prompt.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body>\n  </body>\n</html>",
    grading: {
      method: "llm_judge",
      criteria: [
        { id: "spec_covers_core_elements", description: "The user's spec mentions the app's purpose, at least two core features, and the tech stack.", method: "llm_judge", weight: 2, required: true },
        { id: "output_matches_spec", description: "The generated code reflects what was described in the spec, including the stated features and stack.", method: "llm_judge", weight: 2, required: true },
        { id: "output_is_a_complete_scaffold", description: "The generated code is a working skeleton of the app with the main sections present, not just a single component.", method: "llm_judge", weight: 2, required: true },
      ],
      passingCondition: "All required criteria pass.",
      perfectScore: "All three criteria pass.",
    },
    failState: { condition: "output_matches_spec fails.", nudge: "The output doesn't match what you described. Check if your spec was specific enough about the features and stack you want." },
    successState: { condition: "Passing condition is met.", feedback: "A spec written before you open the AI is the difference between a session that ships and one that spins. You just built the habit." },
    lessonTakeaway: "Writing a spec first forces clarity before you prompt. AI builds better when it gets a complete picture up front.",
  },
  {
    id: CODE_IDS[14],
    title: "Build a full feature in one prompt",
    instruction: "Write a single prompt that builds a complete working feature: a user profile card that fetches data from an API, handles loading and error states, and is fully styled.",
    hint: "Pack everything into one prompt: the stack, the data source, the edge cases, the visual description, and the expected output format. Nothing should be left for AI to guess.",
    starterCode: "<html>\n  <head>\n    <script src=\"https://cdn.tailwindcss.com\"></script>\n  </head>\n  <body class=\"p-8 bg-gray-100\">\n  </body>\n</html>",
    grading: {
      method: "static_analysis + llm_judge",
      criteria: [
        { id: "fetches_real_data", description: "The code fetches data from an API endpoint and renders it in the profile card.", method: "static_analysis", weight: 2, required: true },
        { id: "has_loading_state", description: "The component shows a loading indicator while the data is being fetched.", method: "llm_judge", weight: 2, required: true },
        { id: "has_error_state", description: "The component shows an error message if the fetch fails.", method: "llm_judge", weight: 2, required: true },
        { id: "is_fully_styled", description: "The profile card is visually complete: it has a layout, readable typography, and doesn't look like an unstyled HTML dump.", method: "llm_judge", weight: 1, required: true },
        { id: "prompt_left_nothing_to_guess", description: "The user's prompt specified the stack, the data source, the edge cases, and the visual requirements. AI had no significant gaps to fill.", method: "llm_judge", weight: 1, required: false },
      ],
      passingCondition: "All required criteria pass and total weight score is at least 7 out of 8.",
      perfectScore: "All five criteria pass.",
    },
    failState: { condition: "Any required criterion fails.", nudge: "Something is missing from the output. Go back through your prompt and check: did you specify the stack, the data source, every edge case, and the visual style? Each missing detail is something AI had to guess." },
    successState: { condition: "Passing condition is met.", feedback: "That's a production-level prompt. You gave AI everything it needed and it built everything you asked for. That's what vibe coding looks like when it works." },
    lessonTakeaway: "A complete prompt covers the stack, the data, the edge cases, and the visual requirements. When AI has everything, it builds everything.",
  },
];
